# Generated by Django 2.2.6 on 2019-11-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191021_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Email', models.CharField(blank=True, max_length=200)),
                ('Password', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
